/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // docsSidebar: [ {type: "autogenerated", dirName: "."}]

  // But you can create a sidebar manually
  docs: [
    'welcome',
    'contribution_guide',
    {
      type: 'category',
      label: 'Completor',
      collapsible: false,
      link: {type: 'doc', id: 'about/description'},
      items: ['about/description', 'about/background', 'about/setup', 'about/configuration', 'about/examples'],
    },
    {
      type: 'category',
      label: 'FMU',
      collapsible: false,
      link: {type: 'doc', id: 'fmu/fmu'},
      items: ['fmu/fmu', 'fmu/general_preparations', 'fmu/run_completor'],
    },
  ],
};

export default sidebars;
