name: Run ERT integration test

on:
  workflow_call: # Enables workflow to be called from another workflow.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ERT_SHOW_BACKTRACE: 1

jobs:
  run-ert-test-data:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']

    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Ubuntu dependencies
      run: |
        sudo apt-get update
        sudo apt-get install xvfb libxcb-image0 libxcb-icccm4 libxcb-keysyms1 libxcb-randr0 libxcb-render0 libxcb-render-util0 libxcb-shape0 libxcb-shm0 libxcb-xfixes0 libxcb-xinerama0 libfontconfig1 libxcb-xkb1 libxkbcommon-x11-0 libdbus-1-3

    - name: Install poetry
      run: pipx install poetry==1.8.3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: "poetry"

    - name: Install dependencies
      run: poetry install --with dev -E ert --no-interaction

    - name: List all installed packages
      run: poetry show

    - name: Test completor in ERT
      run: |
        cd tests/completor/data/ert/
        poetry run ert ensemble_experiment ert_test.ert
